added api for profiles, answers, questions
ilukashin/qna pull request #13
Opened 2020-11-10 19:56 UTC by ilukashin

Реализовано API с использованием ActiveModelSerializer для:
Профиля пользователя (/api/v1/profiles/me)
Списка профилей всех пользователей, за исключением аутентифицированного
Списка вопросов
Отдельного вопроса (включает в себя список комментариев, список прикрепленных файлов в виде url и список прикрепленных ссылок)
Списка ответов для вопроса
Отдельного ответа (включает в себя список комментариев, список прикрепленных файлов в виде url и список прикрепленных ссылок)
Создания, редактирования и удаления вопроса (без возможности прикреплять файлы)
Создания ответа для вопроса (без возможности прикреплять файлы)
Редактирования и удаления ответа

2020-11-11 09:57 UTC, IvanShamatov requested changes

2020-11-11 09:57 UTC, IvanShamatov commented on app/controllers/api/v1/answers_controller.rb
> +    if current_resource_owner&.author_of?(@answer)
Привет, 
так, а почему это здесь? это же кусок абилити
**Внимание! Не забывайте использовать авторизацию (проверку прав через CanCan/Pundit) для API!**

2020-11-11 09:57 UTC, IvanShamatov commented on app/controllers/api/v1/answers_controller.rb
> +      render json: { message: 'Not authorized.' }, status: :forbidden
а это кусок неавторизованного входа, который можно в Api::V1::BaseController сложить

2020-11-11 09:57 UTC, IvanShamatov commented on app/controllers/api/v1/questions_controller.rb
> +    if current_resource_owner&.author_of?(@question)
опять, почему-то только здесь забыта авторизация.

2020-11-11 09:57 UTC, IvanShamatov commented on app/serializers/answer_serializer.rb
> +    object.files.map { |file| rails_blob_path(file, only_path: true) }
проверь, у тебя тут не случается N+1?

2020-11-11 09:57 UTC, IvanShamatov commented on app/controllers/api/v1/profiles_controller.rb
> +    render json: @users
имя в сериалайзере аттрибуты email и admin, мы слишком много предоставляем информации пользователю о наших других юзерах. Секурити ишью

2020-11-11 09:57 UTC, IvanShamatov commented on app/controllers/api/v1/questions_controller.rb
> +  skip_authorization_check only: [:destroy]
почему мы тут вообще забиваем на проверку кто это может делать? любой желающий может удалить вопрос?

2020-11-11 09:57 UTC, IvanShamatov commented on spec/api/v1/profiles_spec.rb
> +          expect(json['user'][attr]).to eq me.send(attr).as_json
так, ладно, я не видел видео урока, поэтому не стану судить, но так конечно мало кто делает.
я честно говорят так ине понял, что это за спеки, больше всего похоже на request спеки или контроллер спеки, но было бы неплохо положить их в папочку с этим названием.

https://github.com/thoughtbot/json_matchers. Вот гем чтобы матчить результаты запросов.

Чтобы картина была полной, можно еще (юнит)-спеки на сами сериалайзеры написать

2020-11-11 09:57 UTC, IvanShamatov commented on app/serializers/question_serializer.rb
> +class QuestionSerializer < ActiveModel::Serializer
Стоит похвалить, что ты сделал версированирование у контроллеров. Для АПИ это важно. 
Но рестфульные контроллеры не так часто меняются, как сами данные, которые мы хотим отдавать пользователю, или их представление для пользователя.
Поэтому хорошей практикой будет помимо версионирования контроллеров, еще и версионировать сериалайзеры

2020-11-11 15:55 UTC, ilukashin commented on spec/api/v1/profiles_spec.rb
> +          expect(json['user'][attr]).to eq me.send(attr).as_json
да, такой способ предлагается в скринкасте)
я тоже подумал что если упадет на каком нибудь третьем атрибуте, то непонятно будет, какая проверка свалилась... но подумал что раз такое в видео - значит плохому не должны учить)

2020-11-11 17:18 UTC, ilukashin commented on app/serializers/answer_serializer.rb
> +    object.files.map { |file| rails_blob_path(file, only_path: true) }
на это есть тест
`spec/api/v1/answers_spec.rb:83`
но я проверил через byebug: сколько файлов прикрепили - столько ссылок и возвращается

2020-11-12 07:05 UTC, IvanShamatov approved these changes

2020-11-12 07:31 UTC, merged