Hw16 search
ilukashin/qna pull request #16
Opened 2020-12-05 08:32 UTC by ilukashin

Реализовать функцию поиска по вопросам, ответам, комментариям и пользователям. 
Должна быть возможность совершить общий поиск, сразу по всем возможным объектам, а также возможность поиска отдельно по вопросам/ответам/комментариям/пользователям.

2020-12-05 08:43 UTC, ilukashin commented on app/services/search_service.rb
> +    when :answer then record.question.title
есть подозрение что тут возможен оверхед по запросам к базе.

видел что вроде бы ассоциации можно вытягивать и через эластик, путем имплементации метода as_indexed_json в моделях.

прав ли я и как на самом деле правильнее?

2020-12-05 08:46 UTC, ilukashin commented on spec/features/search/search_spec.rb
> +    [Question, Answer, Comment].each { |model| model.__elasticsearch__.refresh_index! }
такой подход пришлось использовать, т.к. инструкции before, объявленные в rails_helper.rb для спек походу выполняются раньше, чем генерация данных в given/let

и в тестах эти данные получались не индексированными, соотвественно поиск не работал

2020-12-05 08:47 UTC, ilukashin commented on spec/services/search_spec.rb
> +    @results = SearchService.new.search('some text')
такой подход пришлось использовать, т.к. инструкции before, объявленные в rails_helper.rb для спек походу выполняются раньше, чем генерация данных в given/let

и в тестах эти данные получались не индексированными, соотвественно поиск не работал

2020-12-05 11:15 UTC, IvanShamatov requested changes

2020-12-05 11:15 UTC, IvanShamatov commented on app/controllers/comments_controller.rb
> +    redirect_to Comment.find(params[:id]).commentable
А если комментабл у тебя ответ, а не вопрос, то куда ты редиректнешь?

2020-12-05 11:15 UTC, IvanShamatov commented on app/models/answer.rb
> +      indexes :body, type: :text
В этом мапинге полезно еще иметь сам айдишник ответа, а еще лучше айдишник вопроса. Чтобы из резкльтатов можно было бы перейти  на страницу, где есть такой ответ

2020-12-05 11:15 UTC, IvanShamatov commented on app/models/comment.rb
> +      indexes :body, type: :text
Рекомендую больше полей проиндексировать. См выше

2020-12-05 11:15 UTC, IvanShamatov commented on app/models/question.rb
> +      indexes :body, type: :text
Здесь тоже самое про айдишник

2020-12-05 11:15 UTC, IvanShamatov commented on app/services/search_service.rb
> +        id: record.id
Хмм, айдишник значит есть, ну ок

2020-12-05 11:15 UTC, IvanShamatov commented on app/services/search_service.rb
> +  def search(query)
Там где-то в задании было описано, что ты можешь в дропдауне выбрать по чему искать: вопросу, ответу, комменту или по всему сразу. Тут выбор никак не реализован

2020-12-05 11:15 UTC, IvanShamatov commented on app/services/search_service.rb
> +    when :answer then record.question.title
Смотря что за рекорды тебе возвращаются, если active record, то ты тут n+1 делаешь, а если эластик модели, то обращений к базе тут нет

2020-12-05 11:15 UTC, IvanShamatov commented on spec/features/search/search_spec.rb
> +    [Question, Answer, Comment].each { |model| model.__elasticsearch__.refresh_index! }
Да, там какие-то ухищрения, чтоб фабрики делали индексацию

2020-12-05 11:15 UTC, IvanShamatov commented on spec/services/search_spec.rb
> +    @results = SearchService.new.search('some text')
В целом можно было бы записать ответы, и замокать эластик. В конце концов это же тоже 3rd party по отношению к рельсе.

2020-12-07 15:28 UTC, ilukashin commented on app/controllers/comments_controller.rb
> +    redirect_to Comment.find(params[:id]).commentable
в AnswersController#show стоит так же редирект на вопрос.
как я писал, в требованиях не было описания про то, как показывать только ответ.
ну и по логике понятно, что ответ без вопроса врядли имеет смысл. единственно с точки зрения юзабилити можно было бы еще повесить на странице якоря на каждый ответ/коммент, и чтобы там редиректило не просто на вопрос, а на конкретный якорь внутри этого вопроса

2020-12-10 06:34 UTC, IvanShamatov approved these changes

2020-12-10 06:34 UTC, IvanShamatov commented on app/controllers/comments_controller.rb
> +    redirect_to Comment.find(params[:id]).commentable
Если ориентироваться на StackOverflow, то там ссылка на ответ ведет на вопрос и скроллит до ответа с его подсветкой. Из задания непонятно, но в целом вот такой сценарий валиден и понятен. Энивей, я с таким вариантом тоже ок

2020-12-13 08:52 UTC, merged